#!/usr/bin/env python3
"""Column-level lineage tracer for the portifolio dbt project.

Traces a target model column back through the dbt DAG to its raw sources,
using sqlglot to parse each model's *compiled* SQL (ref()/source() already
resolved to real relation names) and dbt's manifest.json to hop from one
model to its parents.

Requires a manifest with `compiled_code` populated, i.e. generated by
`dbt compile` / `dbt build` / `dbt run` — NOT `dbt parse` (which only
discovers the DAG shape, without rendering SQL).

Optionally reads catalog.json (from `dbt docs generate`) to build a column
schema for sqlglot, which lets it expand `SELECT *` and disambiguate
same-named columns across joined tables. Without it, lineage through
`SELECT *` may be incomplete — this is a best-effort enhancement, not a
requirement.

Usage:
    python column_lineage.py mart_api_health service
    python column_lineage.py mart_api_health service --format json
    python column_lineage.py mart_api_health service --format dot > lineage.dot
    python column_lineage.py mart_api_health service --format mermaid
    python column_lineage.py mart_api_health --all-columns --format mermaid
    python column_lineage.py mart_api_health service --manifest ../target/manifest.json
    python column_lineage.py mart_api_health service --package my_pkg
    python column_lineage.py mart_api_health service --dialect snowflake
"""
from __future__ import annotations

import argparse
import importlib.metadata
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import sqlglot
from sqlglot import exp
from sqlglot.errors import SqlglotError
from sqlglot.lineage import lineage as sqlglot_lineage

DEFAULT_MANIFEST = Path(__file__).resolve().parents[1] / "target" / "manifest.json"
DEFAULT_DIALECT = "postgres"
MAX_DEPTH = 15

# This script's parsing assumptions (leaf/Table detection, lineage-tree shape)
# were validated against this sqlglot release. sqlglot's lineage internals are
# not a stable public API and have changed shape across major versions before;
# a mismatch doesn't necessarily mean broken results, but it's worth knowing
# about. Pin this version in requirements.txt for reproducible runs.
TESTED_SQLGLOT_VERSION = "30.18.0"

# dbt adapter_type (from manifest metadata) -> sqlglot dialect name.
# Extend as needed; unrecognized adapters fall back to DEFAULT_DIALECT with a
# warning rather than silently mis-parsing.
ADAPTER_TO_DIALECT = {
    "postgres": "postgres",
    "redshift": "redshift",
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "spark": "spark",
    "databricks": "databricks",
    "duckdb": "duckdb",
    "trino": "trino",
    "presto": "presto",
    "mysql": "mysql",
    "sqlite": "sqlite",
    "clickhouse": "clickhouse",
}

# dbt inlines ephemeral models as CTEs in the downstream compiled SQL, named
# "__dbt__cte__<model_name>". sqlglot's lineage normally traces straight
# through a same-query CTE without ever emitting it as a Table leaf, but if it
# ever does surface one (e.g. an edge case in a particular query shape), we
# want to resolve it back to the ephemeral model rather than reporting an
# unknown relation.
CTE_PREFIX = "__dbt__cte__"


@dataclass
class LineageNode:
    """One hop in a column's ancestry."""

    node: str  # dbt unique_id, or a raw relation key when unresolved
    column: str
    reason: Optional[str] = None  # set only for terminal/unresolved leaves
    file_path: Optional[str] = None  # absolute path to the node's source file, when known
    display: str = ""  # human-readable label ("model:name", "source:src.name", or a raw relation)
    children: list["LineageNode"] = field(default_factory=list)

    @property
    def is_leaf(self) -> bool:
        return not self.children

    def to_dict(self) -> dict:
        d = {"node": self.node, "column": self.column, "display": self.display}
        if self.file_path:
            d["file_path"] = self.file_path
        if self.reason:
            d["reason"] = self.reason
        if self.children:
            d["children"] = [c.to_dict() for c in self.children]
        return d


class ManifestGraph:
    """Lookups over manifest.json (+ optional catalog.json) needed to hop
    across the dbt DAG."""

    def __init__(self, manifest: dict, catalog: Optional[dict] = None, manifest_path: Optional[Path] = None):
        self.metadata: dict = manifest.get("metadata", {})
        self.nodes: dict = manifest["nodes"]
        self.sources: dict = manifest["sources"]
        self._relation_to_id = self._build_relation_index()
        self._cte_name_to_id = self._build_cte_index()
        self.schema: dict = self._build_schema(catalog) if catalog else {}
        # .../target/manifest.json -> project root. Used to resolve every
        # original_file_path (staleness checks, file_path_for) from one place
        # instead of each caller re-deriving it.
        self.project_root: Optional[Path] = manifest_path.resolve().parent.parent if manifest_path else None
        self.manifest_path: Optional[Path] = manifest_path

    def _build_relation_index(self) -> dict[str, str]:
        index: dict[str, str] = {}
        for unique_id, source in self.sources.items():
            key = _relation_key(source.get("database"), source.get("schema"), source.get("identifier"))
            index[key] = unique_id
        for unique_id, node in self.nodes.items():
            identifier = node.get("alias") or node.get("name")
            key = _relation_key(node.get("database"), node.get("schema"), identifier)
            index[key] = unique_id
        return index

    def _build_cte_index(self) -> dict[str, str]:
        """Maps dbt's ephemeral-model CTE alias ("__dbt__cte__<name>") back to
        the model's unique_id, as a fallback for when an ephemeral model
        surfaces as a Table leaf instead of being traced through inline."""
        index: dict[str, str] = {}
        for unique_id, node in self.nodes.items():
            if node.get("resource_type") == "model":
                index[f"{CTE_PREFIX}{node.get('name')}"] = unique_id
        return index

    def _build_schema(self, catalog: dict) -> dict:
        """Builds a nested {database: {schema: {table: {col: type}}}} mapping
        from catalog.json for sqlglot, so it can expand SELECT * and
        disambiguate same-named columns across joined tables."""
        schema: dict = {}
        for entry in {**catalog.get("sources", {}), **catalog.get("nodes", {})}.values():
            meta = entry.get("metadata", {})
            database, db_schema, name = meta.get("database"), meta.get("schema"), meta.get("name")
            if not (database and db_schema and name):
                continue
            columns = entry.get("columns", {})
            col_types = {col_name: (col.get("type") or "unknown") for col_name, col in columns.items()}
            if col_types:
                schema.setdefault(database, {}).setdefault(db_schema, {})[name] = col_types
        return schema

    def schema_for_sql(self, sql: str, dialect: str) -> Optional[dict]:
        """Returns graph.schema if it's usable for this specific query, else
        None. sqlglot's optimizer treats a passed-in schema as authoritative:
        a table the schema doesn't cover doesn't just stay unresolved the way
        it would with no schema at all, its columns become unresolvable
        placeholders — worse than passing nothing. That can happen from an
        incomplete catalog.json, or routinely from an inlined ephemeral-model
        CTE, which never has a catalog entry since it's never materialized.
        So: only use the schema when every *real* (non-CTE) relation the
        query touches is covered by it; otherwise fall back to no schema at
        all, which is safe for every case, just less precise for SELECT *."""
        if not self.schema:
            return None
        try:
            parsed = sqlglot.parse_one(sql, dialect=dialect)
        except SqlglotError:
            return None
        cte_names = {cte.alias_or_name for cte in parsed.find_all(exp.CTE)}
        for table in parsed.find_all(exp.Table):
            if table.name in cte_names:
                continue  # reference to a locally-defined CTE, not a real relation
            cols = self.schema.get(table.catalog or None, {}).get(table.db or None, {}).get(table.name)
            if not cols:
                return None
        return self.schema

    def is_source(self, unique_id: str) -> bool:
        return unique_id in self.sources

    def compiled_sql(self, unique_id: str) -> Optional[str]:
        node = self.nodes.get(unique_id)
        return node.get("compiled_code") if node else None

    def resolve_relation(self, database: Optional[str], schema: Optional[str], name: Optional[str]) -> Optional[str]:
        direct = self._relation_to_id.get(_relation_key(database, schema, name))
        if direct is not None:
            return direct
        if name and name in self._cte_name_to_id:
            return self._cte_name_to_id[name]
        return None

    def display(self, unique_id: str) -> str:
        if unique_id in self.sources:
            source = self.sources[unique_id]
            return f"source:{source.get('source_name')}.{source.get('name')}"
        node = self.nodes.get(unique_id)
        if not node:
            return unique_id
        return f"{node.get('resource_type', 'model')}:{node.get('name', unique_id)}"

    def file_path_for(self, unique_id: str) -> Optional[str]:
        """Absolute path to the file that declares this node — a model's
        .sql file, or a source's .yml — so a consumer (the text/graph
        formatters, or the VS Code extension) can jump straight to it
        without re-deriving the project root or re-reading the manifest."""
        node = self.nodes.get(unique_id) or self.sources.get(unique_id)
        if not node:
            return None
        rel = node.get("original_file_path") or node.get("path")
        if not rel:
            return None
        return str((self.project_root / rel)) if self.project_root else rel

    def model_columns(self, unique_id: str, dialect: str) -> list[str]:
        """Returns the model's output columns, for --all-columns mode. Tries,
        in order of trustworthiness: (1) catalog.json, since it reflects the
        real materialized columns straight from the warehouse and handles
        `SELECT *` correctly; (2) parsing the compiled SQL's final projection
        with sqlglot, which is exact even when catalog.json isn't available,
        except through an unresolved `SELECT *`; (3) the column names
        documented in the model's schema.yml, which may be incomplete or
        stale but are better than nothing."""
        node = self.nodes.get(unique_id, {})
        database, db_schema = node.get("database"), node.get("schema")
        identifier = node.get("alias") or node.get("name")
        catalog_cols = self.schema.get(database, {}).get(db_schema, {}).get(identifier)
        if catalog_cols:
            return list(catalog_cols.keys())

        sql = self.compiled_sql(unique_id)
        if sql:
            try:
                parsed = sqlglot.parse_one(sql, dialect=dialect)
                cols = [c for c in parsed.named_selects if c and c != "*"]
                if cols:
                    return cols
            except SqlglotError:
                pass

        return list((node.get("columns") or {}).keys())

    def find_models(self, model_name: str, package: Optional[str] = None) -> list[tuple[str, dict]]:
        """Returns all (unique_id, node) pairs matching a model name, optionally
        narrowed by dbt package name to resolve cross-package name collisions
        in monorepos."""
        candidates = [
            (uid, n) for uid, n in self.nodes.items()
            if n.get("name") == model_name and uid.startswith("model.")
        ]
        if package:
            candidates = [(uid, n) for uid, n in candidates if n.get("package_name") == package]
        return candidates


def _relation_key(database: Optional[str], schema: Optional[str], name: Optional[str]) -> str:
    return f"{database}.{schema}.{name}".lower()


def _bare_column_name(qualified_name: str) -> str:
    """sqlglot lineage node names look like '\"alias\".\"col\"' — take the last part."""
    return qualified_name.rsplit(".", 1)[-1].strip('"`\'')


def _node(graph: ManifestGraph, unique_id: str, column: str, reason: Optional[str] = None) -> LineageNode:
    """Builds a LineageNode for a real graph unique_id (model or source),
    filling in its display label and source file path from the manifest right
    away. Every LineageNode in a trace is built through this (the one
    exception is the synthetic "relation-not-in-manifest" leaf, which by
    definition has no unique_id to look up) so display/file_path are always
    populated consistently, and the tree/graph formatters — and the JSON any
    external consumer like the VS Code extension reads — never need to
    re-touch the manifest themselves."""
    return LineageNode(
        unique_id, column, reason=reason,
        file_path=graph.file_path_for(unique_id),
        display=graph.display(unique_id),
    )


def trace_column(
    graph: ManifestGraph,
    unique_id: str,
    column: str,
    dialect: str = DEFAULT_DIALECT,
    depth: int = 0,
    path: Optional[frozenset] = None,
    memo: Optional[dict[tuple[str, str], LineageNode]] = None,
) -> LineageNode:
    """Recursively resolve `column`'s ancestry starting at dbt node `unique_id`.

    `path` holds only the current chain of ancestors (for real-cycle
    detection); `memo` caches fully-resolved (unique_id, column) subtrees
    across the whole trace so the same node reached via two different
    branches — e.g. two sibling models that both derive from the same
    upstream column, a very common "diamond" shape in dbt DAGs — is computed
    once and correctly recognized as shared lineage, not a cycle.
    """
    path = path if path is not None else frozenset()
    memo = memo if memo is not None else {}
    key = (unique_id, column)

    if key in memo:
        return memo[key]
    if key in path:
        return _node(graph, unique_id, column, reason="cycle-detected")
    if depth > MAX_DEPTH:
        return _node(graph, unique_id, column, reason="max-depth-exceeded")

    if graph.is_source(unique_id):
        result = _node(graph, unique_id, column, reason="raw-source")
        memo[key] = result
        return result

    sql = graph.compiled_sql(unique_id)
    if not sql:
        result = _node(graph, unique_id, column, reason="no-compiled-sql (run `dbt compile`)")
        memo[key] = result
        return result

    try:
        root = sqlglot_lineage(column, sql, schema=graph.schema_for_sql(sql, dialect), dialect=dialect)
    except SqlglotError as e:
        result = _node(graph, unique_id, column, reason=f"sqlglot-parse-error: {e}")
        memo[key] = result
        return result

    child_path = path | {key}
    result = _node(graph, unique_id, column)
    for leaf in _leaves(root):
        if leaf is root:
            # The column had no traceable FROM source (e.g. a literal/constant).
            continue

        table = leaf.expression if isinstance(leaf.expression, exp.Table) else None
        if table is None:
            result.children.append(_node(graph, unique_id, column, reason="non-table-expression (literal/computed)"))
            continue

        leaf_column = _bare_column_name(leaf.name)
        parent_id = graph.resolve_relation(table.catalog or None, table.db or None, table.name)
        if parent_id is None:
            raw_relation = ".".join(p for p in (table.catalog, table.db, table.name) if p)
            result.children.append(
                LineageNode(raw_relation, leaf_column, reason="relation-not-in-manifest", display=raw_relation)
            )
            continue

        result.children.append(trace_column(graph, parent_id, leaf_column, dialect, depth + 1, child_path, memo))

    if not result.children:
        result.reason = "terminal-select (no upstream columns found)"

    memo[key] = result
    return result


def _leaves(node) -> list:
    if not node.downstream:
        return [node]
    found = []
    for child in node.downstream:
        found.extend(_leaves(child))
    return found


def format_tree(node: LineageNode, depth: int = 0) -> str:
    label = node.display
    connector = "└─ " if depth > 0 else ""
    line = f"{'   ' * depth}{connector}{label}.{node.column}"
    if node.reason:
        line += f"  [{node.reason}]"
    lines = [line]
    for child in node.children:
        lines.append(format_tree(child, depth + 1))
    return "\n".join(lines)


def _node_id(node: LineageNode) -> str:
    """Identity key for a lineage node in graph output. Deliberately the same
    (unique_id, column) key trace_column memoizes on, so a column reached via
    two different branches — the diamond case — collapses into one graph
    node with two incoming edges instead of being drawn twice, and a real
    cycle renders as an edge back onto an already-drawn node instead of
    recursing forever."""
    return f"{node.node}\u241f{node.column}"  # \u241f: unlikely to collide with real names


def _node_label(node: LineageNode) -> str:
    return f"{node.display}.{node.column}"


_ISSUE_REASONS = {
    "no-compiled-sql (run `dbt compile`)",
    "sqlglot-parse-error",  # prefix-matched below, since it includes the exception text
    "relation-not-in-manifest",
    "max-depth-exceeded",
    "non-table-expression (literal/computed)",
    "terminal-select (no upstream columns found)",
}


def _node_category(node: LineageNode) -> str:
    if node.reason == "raw-source":
        return "source"
    if node.reason == "cycle-detected":
        return "cycle"
    if node.reason and (node.reason in _ISSUE_REASONS or node.reason.startswith("sqlglot-parse-error")):
        return "issue"
    return "model"


def build_graph(
    roots: list[LineageNode],
) -> tuple[dict[str, LineageNode], list[tuple[str, str]], set[str]]:
    """Flattens one or more lineage trees into a deduplicated node/edge list
    suitable for Graphviz or Mermaid. Multiple roots let --all-columns render
    every traced column's lineage as a single combined graph, sharing any
    ancestors the columns have in common rather than repeating them."""
    nodes: dict[str, LineageNode] = {}
    edges: list[tuple[str, str]] = []
    edge_set: set[tuple[str, str]] = set()
    expanded: set[str] = set()
    root_ids: set[str] = set()

    def walk(node: LineageNode) -> None:
        nid = _node_id(node)
        if nid not in nodes:
            nodes[nid] = node
        if nid in expanded:
            return
        expanded.add(nid)
        for child in node.children:
            cid = _node_id(child)
            edge = (nid, cid)
            if edge not in edge_set:
                edge_set.add(edge)
                edges.append(edge)
            walk(child)

    for root in roots:
        root_ids.add(_node_id(root))
        walk(root)

    return nodes, edges, root_ids


def _dot_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def to_dot(roots: list[LineageNode], title: str = "lineage") -> str:
    nodes, edges, root_ids = build_graph(roots)
    style_by_category = {
        "source": 'style=filled, fillcolor="#cfe8ff"',
        "issue": 'style=filled, fillcolor="#fff3cd"',
        "cycle": 'style=filled, fillcolor="#ffd6d6", peripheries=2',
        "model": 'style=filled, fillcolor="#f2f2f2"',
    }
    lines = [
        f'digraph "{_dot_escape(title)}" {{',
        "  rankdir=LR;",
        '  node [shape=box, fontname="Helvetica", fontsize=10];',
    ]
    for nid, node in nodes.items():
        style = style_by_category[_node_category(node)]
        if nid in root_ids:
            style += ", penwidth=2"
        # The literal \n below is Graphviz's own line-break escape inside a
        # label and must survive un-mangled; only the dynamic text around it
        # (which may contain a sqlglot error message) goes through
        # _dot_escape.
        label = _dot_escape(_node_label(node))
        if node.reason:
            label += f"\\n[{_dot_escape(node.reason)}]"
        lines.append(f'  "{_dot_escape(nid)}" [label="{label}", {style}];')
    # Arrows are drawn ancestor -> descendant (source flows into the
    # mart), the reverse of how `edges` is built internally (target depends
    # on ancestor) — this is what makes rankdir=LR read left-to-right the
    # way a data pipeline is conventionally drawn, source on the left.
    for src, dst in edges:
        lines.append(f'  "{_dot_escape(dst)}" -> "{_dot_escape(src)}";')
    lines.append("}")
    return "\n".join(lines)


def to_mermaid(roots: list[LineageNode]) -> str:
    nodes, edges, root_ids = build_graph(roots)
    id_map = {nid: f"n{i}" for i, nid in enumerate(nodes)}
    shape_by_category = {
        "source": ("([", "])"),
        "issue": ("{{", "}}"),
        "cycle": ("{{", "}}"),
        "model": ("[", "]"),
    }
    class_by_category = {"source": "src", "issue": "issue", "cycle": "cyc", "model": "mdl"}

    lines = ["flowchart LR"]
    by_class: dict[str, list[str]] = {}
    for nid, node in nodes.items():
        category = _node_category(node)
        open_s, close_s = shape_by_category[category]
        label = (_node_label(node) + (f"<br/>[{node.reason}]" if node.reason else "")).replace('"', "'")
        mid = id_map[nid]
        lines.append(f'  {mid}{open_s}"{label}"{close_s}')
        by_class.setdefault(class_by_category[category], []).append(mid)
        if nid in root_ids:
            by_class.setdefault("root", []).append(mid)

    # Same reversal as to_dot: draw ancestor -> descendant so `flowchart LR`
    # puts the raw source on the left and the traced mart on the right.
    for src, dst in edges:
        lines.append(f"  {id_map[dst]} --> {id_map[src]}")

    lines.append("  classDef src fill:#cfe8ff,stroke:#5b9bd5,color:#0b3550")
    lines.append("  classDef issue fill:#fff3cd,stroke:#d4a017,color:#4a3800")
    lines.append("  classDef cyc fill:#ffd6d6,stroke:#cc4444,color:#5a1010")
    lines.append("  classDef mdl fill:#f2f2f2,stroke:#999999,color:#1a1a1a")
    lines.append("  classDef root stroke-width:3px")
    for class_name, ids in by_class.items():
        lines.append(f"  class {','.join(ids)} {class_name}")

    return "\n".join(lines)


def _load_json_required(path: Path, label: str) -> dict:
    """Loads a required JSON file, exiting with a clear message on any failure
    instead of letting a raw traceback surface for a malformed file."""
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"error: {label} not found at {path} (run `dbt compile` first)", file=sys.stderr)
        raise SystemExit(1)
    except json.JSONDecodeError as e:
        print(f"error: {label} at {path} is not valid JSON: {e}", file=sys.stderr)
        raise SystemExit(1)
    except OSError as e:
        print(f"error: could not read {label} at {path}: {e}", file=sys.stderr)
        raise SystemExit(1)


def _load_json_optional(path: Optional[Path], label: str) -> dict:
    """Loads an optional JSON file (e.g. catalog.json). Missing or unreadable
    is a warning, not a fatal error — the tool degrades to no-schema mode."""
    if path is None or not path.exists():
        return {}
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        print(f"warning: could not read {label} at {path} ({e}); continuing without it", file=sys.stderr)
        return {}


def _check_sqlglot_version() -> None:
    try:
        installed = importlib.metadata.version("sqlglot")
    except importlib.metadata.PackageNotFoundError:
        return
    if installed != TESTED_SQLGLOT_VERSION:
        print(
            f"warning: validated against sqlglot=={TESTED_SQLGLOT_VERSION}, found {installed}. "
            f"sqlglot's lineage internals aren't a stable public API, so results may differ "
            f"between versions — pin the tested version in requirements.txt if you hit surprises.",
            file=sys.stderr,
        )


def _check_staleness(graph: ManifestGraph) -> None:
    """Best-effort warning if a model's source file looks newer than the
    manifest, suggesting lineage may be computed from stale compiled SQL.
    Never raises — failures here should never block a trace."""
    if graph.project_root is None:
        return
    try:
        manifest_mtime = graph.manifest_path.stat().st_mtime
        project_root = graph.project_root
        stale = sorted({
            node.get("name", uid)
            for uid, node in graph.nodes.items()
            if uid.startswith("model.")
            and node.get("original_file_path")
            and (project_root / node["original_file_path"]).exists()
            and (project_root / node["original_file_path"]).stat().st_mtime > manifest_mtime
        })
        if stale:
            shown = ", ".join(stale[:5])
            more = "" if len(stale) <= 5 else f" (+{len(stale) - 5} more)"
            print(
                f"warning: {len(stale)} model file(s) newer than manifest.json (e.g. {shown}{more}) — "
                f"lineage may be stale; consider re-running `dbt compile`",
                file=sys.stderr,
            )
    except OSError:
        pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("model", help="dbt model name (as declared in the manifest, e.g. mart_api_health)")
    parser.add_argument(
        "column", nargs="?", default=None,
        help="column name to trace; omit and pass --all-columns to trace every output column instead",
    )
    parser.add_argument(
        "--all-columns", action="store_true",
        help="trace every output column of the model in one run, reusing a single lineage cache across "
             "them so shared ancestors are computed once",
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="path to manifest.json")
    parser.add_argument(
        "--catalog", type=Path, default=None,
        help="path to catalog.json (from `dbt docs generate`); enables SELECT * expansion. "
             "Defaults to catalog.json next to the manifest, if present.",
    )
    parser.add_argument(
        "--dialect", default=None,
        help="sqlglot SQL dialect. Defaults to the dialect inferred from the manifest's adapter_type.",
    )
    parser.add_argument(
        "--package", default=None,
        help="dbt package name, to disambiguate when --model matches more than one package (monorepos)",
    )
    parser.add_argument(
        "--format", choices=["tree", "json", "dot", "mermaid"], default=None,
        help="output format (default: tree). 'dot' and 'mermaid' render the lineage as a graph, with "
             "shared ancestors deduplicated rather than repeated",
    )
    parser.add_argument("--json", action="store_true", help="[deprecated, use --format json]")
    parser.add_argument("--no-staleness-check", action="store_true", help="skip the manifest-freshness warning")
    args = parser.parse_args()

    if args.column and args.all_columns:
        parser.error("pass either a column or --all-columns, not both")
    if not args.column and not args.all_columns:
        parser.error("a column is required unless --all-columns is passed")

    _check_sqlglot_version()

    manifest = _load_json_required(args.manifest, "manifest")
    catalog_path = args.catalog if args.catalog is not None else args.manifest.parent / "catalog.json"
    catalog = _load_json_optional(catalog_path, "catalog")

    graph = ManifestGraph(manifest, catalog, manifest_path=args.manifest)

    if not args.no_staleness_check:
        _check_staleness(graph)

    candidates = graph.find_models(args.model, args.package)
    if not candidates:
        scope = f" in package '{args.package}'" if args.package else ""
        print(f"error: model '{args.model}'{scope} not found in manifest", file=sys.stderr)
        return 1
    if len(candidates) > 1:
        print(f"error: model '{args.model}' is ambiguous — found in multiple packages:", file=sys.stderr)
        for uid, node in candidates:
            print(f"  --package {node.get('package_name')}  ({uid})", file=sys.stderr)
        print("pass --package to disambiguate", file=sys.stderr)
        return 1
    unique_id = candidates[0][0]

    if args.dialect:
        dialect = args.dialect
    else:
        adapter_type = graph.metadata.get("adapter_type")
        dialect = ADAPTER_TO_DIALECT.get(adapter_type, DEFAULT_DIALECT)
        if adapter_type and adapter_type not in ADAPTER_TO_DIALECT:
            print(
                f"warning: unrecognized adapter_type '{adapter_type}' in manifest; "
                f"falling back to dialect '{DEFAULT_DIALECT}'. Pass --dialect to override.",
                file=sys.stderr,
            )

    if args.all_columns:
        columns = graph.model_columns(unique_id, dialect)
        if not columns:
            print(
                f"error: could not determine output columns for model '{args.model}' — no catalog.json "
                f"entry, unparseable compiled SQL, and no documented columns in the manifest",
                file=sys.stderr,
            )
            return 1
        memo: dict[tuple[str, str], LineageNode] = {}
        results = [(col, trace_column(graph, unique_id, col, dialect=dialect, memo=memo)) for col in columns]
    else:
        results = [(args.column, trace_column(graph, unique_id, args.column, dialect=dialect))]

    fmt = args.format or ("json" if args.json else "tree")
    roots = [node for _, node in results]

    if fmt == "json":
        payload = {col: node.to_dict() for col, node in results} if args.all_columns else roots[0].to_dict()
        print(json.dumps(payload, indent=2))
    elif fmt == "dot":
        print(to_dot(roots, title=args.model))
    elif fmt == "mermaid":
        print(to_mermaid(roots))
    else:
        for col, node in results:
            if args.all_columns:
                print(f"=== {col} ===")
            print(format_tree(node))
            if args.all_columns:
                print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
